-- Check for orphaned data (data without a valid profile)
SELECT 'notifications' as table_name, COUNT(*) as count FROM notifications WHERE user_id NOT IN (SELECT id FROM profiles)
UNION ALL SELECT 'messages (sender)', COUNT(*) FROM messages WHERE sender_id NOT IN (SELECT id FROM profiles)
UNION ALL SELECT 'messages (receiver)', COUNT(*) FROM messages WHERE receiver_id NOT IN (SELECT id FROM profiles)
UNION ALL SELECT 'forum_posts', COUNT(*) FROM forum_posts WHERE author_id NOT IN (SELECT id FROM profiles)
UNION ALL SELECT 'forum_comments', COUNT(*) FROM forum_comments WHERE author_id NOT IN (SELECT id FROM profiles)
UNION ALL SELECT 'likes', COUNT(*) FROM likes WHERE user_id NOT IN (SELECT id FROM profiles)
UNION ALL SELECT 'bookmarks', COUNT(*) FROM bookmarks WHERE user_id NOT IN (SELECT id FROM profiles)
UNION ALL SELECT 'event_registrations', COUNT(*) FROM event_registrations WHERE user_id NOT IN (SELECT id FROM profiles)
UNION ALL SELECT 'reviews', COUNT(*) FROM reviews WHERE user_id NOT IN (SELECT id FROM profiles)
UNION ALL SELECT 'vendors', COUNT(*) FROM vendors WHERE owner_id NOT IN (SELECT id FROM profiles)
UNION ALL SELECT 'subscriptions', COUNT(*) FROM subscriptions WHERE user_id NOT IN (SELECT id FROM profiles)
UNION ALL SELECT 'payments', COUNT(*) FROM payments WHERE user_id NOT IN (SELECT id FROM profiles)
UNION ALL SELECT 'blog_posts', COUNT(*) FROM blog_posts WHERE author_id NOT IN (SELECT id FROM profiles)
UNION ALL SELECT 'resources', COUNT(*) FROM resources WHERE author_id NOT IN (SELECT id FROM profiles)
UNION ALL SELECT 'events', COUNT(*) FROM events WHERE organizer_id NOT IN (SELECT id FROM profiles);